# Base Images
## 从天池基础镜像构建(from的base img 根据自己的需要更换，建议使用天池open list镜像链接：https://tianchi.aliyun.com/forum/postDetail?postId=67720)
FROM registry.cn-shanghai.aliyuncs.com/tcc_public/python:3.10

#-----------------------------新版环境--------------------------------------
RUN pip install torch==2.4.0 torchvision==0.19.0 torchaudio --index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install transformers==4.44.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install peft -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pandas==2.2.2 -i https://pypi.tuna.tsinghua.edu.cn/simple 
RUN pip install tqdm -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install vllm==0.5.4 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install FlagEmbedding==1.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install openai loguru httpx -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install sentence-transformers==3.1.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install datasets==2.19.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install faiss-cpu -i https://pypi.tuna.tsinghua.edu.cn/simple
WORKDIR /app
RUN mkdir /app/data

# step0: 再image下
# docker build -t test:v1                               
# step1：把上级的data 直接挂载成 容器的 /app
# docker run -d -v {绝对路径}/data/:/app test:v1 sleep infinity
# docker run -d -v ./data:/app/data test:v1 sleep infinity
# step2: 进去容器 docker ps 查看容器id
# docker exec -it {容器id} bash
# step3: 执行run.sh
# 里面去执行 sh -x data/code/run.sh

